package com.nuapro.pages;

import com.nuapro.utils.WaitUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

public class InvitationCodesPage {

    private final WebDriver driver;
    private final WaitUtils waitUtils;

    // The current React UI uses action buttons that open MUI dialogs; it no
    // longer exposes the former Add Code / Auto Codes route tabs.
    private final By openAddCodeDialogButton = By.cssSelector(".invitation_code_subtabs_list button.addCode");
    private final By addCodeDialog = By.cssSelector(".MuiDialog-root.openNuaTabsModal.add-codes-modal");
    private final By codeTitleInput = By.cssSelector(".MuiDialog-root.openNuaTabsModal.add-codes-modal textarea#add_invite_code");
    private final By codeUsesInput = By.cssSelector(".MuiDialog-root.openNuaTabsModal.add-codes-modal input[name='invite_code_usage_limit']");
    private final By saveCodeButton = By.cssSelector(".MuiDialog-root.openNuaTabsModal.add-codes-modal button.importBtn");

    private final By openAutoGenerateDialogButton = By.cssSelector(".invitation_code_subtabs_list button.autoGenerator");
    private final By autoGenerateDialog = By.xpath("//div[contains(concat(' ', normalize-space(@class), ' '), ' MuiDialog-root ')][.//input[@name='code-quantity']]");
    private final By autoCodeCountInput = By.xpath("//div[contains(concat(' ', normalize-space(@class), ' '), ' MuiDialog-root ')][.//input[@name='code-quantity']]//input[@name='code-quantity']");
    private final By autoCodeUsesInput = By.xpath("//div[contains(concat(' ', normalize-space(@class), ' '), ' MuiDialog-root ')][.//input[@name='code-quantity']]//input[@name='auto-code-usageLimit']");
    private final By generateCodesButton = By.xpath("//div[contains(concat(' ', normalize-space(@class), ' '), ' MuiDialog-root ')][.//input[@name='code-quantity']]//button[contains(normalize-space(.), 'Generate')]");

    public InvitationCodesPage(WebDriver driver) {
        this.driver = driver;
        this.waitUtils = new WaitUtils(driver);
    }

    public InvitationCodesPage clickAddCodeTab() {
        waitUtils.clickElement(openAddCodeDialogButton);
        waitUtils.waitForVisibility(addCodeDialog);
        return this;
    }

    public InvitationCodesPage clickAutoCodesTab() {
        waitUtils.clickElement(openAutoGenerateDialogButton);
        waitUtils.waitForVisibility(autoGenerateDialog);
        return this;
    }

    public void createManualCode(String title, int uses) {
        clickAddCodeTab();
        waitUtils.sendKeys(codeTitleInput, title);
        waitUtils.sendKeys(codeUsesInput, String.valueOf(uses));
        waitUtils.clickElement(saveCodeButton);
        waitUtils.waitForLoaderToDisappear();
        waitUtils.waitForToast();
        closeAddCodeDialogIfOpen();
    }

    public void autoGenerateCodes(int count) {
        clickAutoCodesTab();
        waitUtils.sendKeys(autoCodeCountInput, String.valueOf(count));
        // Usage limit is required by the current dialog and has no default.
        waitUtils.sendKeys(autoCodeUsesInput, "1");
        waitUtils.clickElement(generateCodesButton);
        waitUtils.waitForLoaderToDisappear();
        waitUtils.waitForInvisibility(autoGenerateDialog);
    }

    public boolean isCodePresentInList(String codeTitle) {
        By codeRowLocator = By.xpath("//tr[descendant::*[contains(text(), '" + codeTitle + "')]]");
        try {
            return waitUtils.waitForVisibility(codeRowLocator).isDisplayed();
        } catch (Exception e) {
            return false;
        }
    }

    public void deleteCode(String codeTitle) {
        By codeRowLocator = By.xpath("//tr[descendant::*[contains(text(), '" + codeTitle + "')]]");
        WebElement row = waitUtils.waitForVisibility(codeRowLocator);
        java.util.List<WebElement> actionButtons = row.findElements(By.cssSelector("td.actionsRow button"));
        WebElement deleteButton = actionButtons.stream()
                .filter(button -> {
                    try {
                        return button.isDisplayed() && button.isEnabled();
                    } catch (Exception ignored) {
                        return false;
                    }
                })
                .reduce((first, second) -> second)
                .orElse(null);
        if (deleteButton == null) {
            throw new IllegalStateException("No invitation-code action buttons found for " + codeTitle);
        }
        deleteButton.click();
        waitUtils.waitForVisibility(By.cssSelector(".MuiDialog-root.delete-inv-modal .delete-confirmation"));
        waitUtils.clickElement(By.cssSelector(".MuiDialog-root.delete-inv-modal .importBtn"));
        waitUtils.waitForInvisibility(By.cssSelector(".MuiDialog-root.delete-inv-modal"));
    }

    private void closeAddCodeDialogIfOpen() {
        if (driver.findElements(addCodeDialog).stream().anyMatch(button -> {
            try {
                return button.isDisplayed();
            } catch (Exception ignored) {
                return false;
            }
        })) {
            waitUtils.clickElement(By.cssSelector(".MuiDialog-root.openNuaTabsModal.add-codes-modal .nua-modal-close"));
        }
    }
}
